version: '3.8'

services:
  # Application service for development
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/ielts_mock_dev
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    command: npm run dev
    restart: unless-stopped
    networks:
      - ielts-network-dev

  # MongoDB service for development
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-ielts_mock_dev}
    volumes:
      - mongo_data_dev:/data/db
    restart: unless-stopped
    networks:
      - ielts-network-dev

  # Redis service for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    restart: unless-stopped
    networks:
      - ielts-network-dev

volumes:
  mongo_data_dev:
  redis_data_dev:

networks:
  ielts-network-dev:
    driver: bridge